import { expect, test } from '@playwright/test'

test('the adventure supports real keyboard movement, pause, resume, and restart', async ({ page }) => {
  await page.goto('/')
  const world = page.getByTestId('play-world')
  const progress = page.getByTestId('play-progress')
  await expect(world).toHaveAttribute('data-state', 'ready')
  await page.keyboard.press('ArrowRight')
  await expect(world).toHaveAttribute('data-state', 'ready')
  await page.getByTestId('play-start').click()
  await expect(world).toHaveAttribute('data-state', 'playing')
  await expect(world).toBeFocused()
  await page.keyboard.down('ArrowRight')
  await expect.poll(async () => Number(await progress.getAttribute('value')), { timeout: 5000 }).toBeGreaterThan(4)
  await page.keyboard.down('Space')
  await expect(page.getByTestId('play-jump')).toHaveAttribute('data-active', 'true')
  await page.keyboard.up('Space')
  await page.keyboard.up('ArrowRight')
  await expect(page.getByTestId('play-jump')).toHaveAttribute('data-active', 'false')
  await page.keyboard.press('KeyP')
  await expect(world).toHaveAttribute('data-state', 'paused')
  const pausedProgress = await progress.getAttribute('value')
  await page.waitForTimeout(300)
  await expect(progress).toHaveAttribute('value', pausedProgress!)
  await page.getByTestId('play-resume').click()
  await expect(world).toHaveAttribute('data-state', 'playing')
  await expect(world).toBeFocused()
  await page.getByRole('button', { name: 'Restart world' }).click()
  await expect(progress).toHaveAttribute('value', '0')
  await expect(page.getByTestId('play-score')).toHaveAttribute('aria-label', '0 of 16 data tokens collected')
})

test('the guided tour genuinely reaches the end and offers a working next step', async ({ page }) => {
  test.setTimeout(75_000)
  await page.goto('/')
  const world = page.getByTestId('play-world')
  await page.getByTestId('play-tour').click()
  await expect(world).toHaveAttribute('data-mode', 'tour')
  await expect(world).toHaveAttribute('data-state', 'playing')
  await expect(page.getByTestId('play-completion')).toBeVisible({ timeout: 60_000 })
  await expect(world).toHaveAttribute('data-state', 'complete')
  await expect(page.getByTestId('play-progress')).toHaveAttribute('value', '100')
  await expect(page.locator('.play-checkpoint-count')).toHaveAttribute('aria-label', '4 of 4 checkpoints explored')
  const score = await page.getByTestId('play-score').getAttribute('aria-label')
  expect(Number(score?.split(' ')[0])).toBeGreaterThan(0)
  await expect(page.getByTestId('play-completion').getByRole('link', { name: 'Get the résumé' })).toHaveAttribute('href', '/resume/Roushan-Kumar-Resume.pdf')
  await page.getByTestId('play-completion').getByRole('button', { name: /build something/ }).click()
  await expect(page.getByRole('dialog').getByLabel('Your email')).toBeVisible()
})

test('manual takeover and leaving the game clear movement safely', async ({ page }) => {
  await page.goto('/')
  const world = page.getByTestId('play-world')
  await page.getByTestId('play-tour').click()
  await page.getByTestId('play-take-control').click()
  await expect(world).toHaveAttribute('data-mode', 'manual')
  await expect(world).toBeFocused()
  await page.keyboard.down('ArrowRight')
  await expect(page.getByTestId('play-right')).toHaveAttribute('data-active', 'true')
  await page.getByRole('link', { name: 'Skip game / View portfolio', exact: true }).focus()
  await page.keyboard.up('ArrowRight')
  await expect(world).toHaveAttribute('data-state', 'paused')
  await expect(page.getByTestId('play-right')).toHaveAttribute('data-active', 'false')
  await page.getByTestId('play-resume').click()
  await page.evaluate(() => window.dispatchEvent(new Event('blur')))
  await expect(world).toHaveAttribute('data-state', 'paused')
  await expect(page.getByText('The window lost focus. Nothing was lost.', { exact: true })).toBeVisible()
})

test('mobile touch controls move the player and release on touch cancellation', async ({ page, context }, testInfo) => {
  test.skip(testInfo.project.name !== 'mobile', 'Real touch emulation on the mobile browser')
  await page.goto('/')
  await page.getByTestId('play-start').click()
  const move = page.getByTestId('play-right')
  const box = await move.boundingBox()
  if (!box) throw new Error('The on-screen Move right control is not visible.')
  const session = await context.newCDPSession(page)
  await session.send('Input.dispatchTouchEvent', {
    type: 'touchStart',
    touchPoints: [{ x: box.x + box.width / 2, y: box.y + box.height / 2, id: 1 }],
  })
  await expect(move).toHaveAttribute('data-active', 'true')
  await expect.poll(async () => Number(await page.getByTestId('play-progress').getAttribute('value')), { timeout: 5000 }).toBeGreaterThan(3)
  await session.send('Input.dispatchTouchEvent', { type: 'touchCancel', touchPoints: [] })
  await expect(move).toHaveAttribute('data-active', 'false')
  await page.getByRole('button', { name: 'Pause game', exact: true }).click()
  await expect(page.getByTestId('play-world')).toHaveAttribute('data-state', 'paused')
  await session.detach()
})

test('the full portfolio and every case study are accessible without winning', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('link', { name: 'Skip game / View portfolio', exact: true }).click()
  await expect(page).toHaveURL(/#play-portfolio$/)
  await expect(page.locator('#play-portfolio')).toBeVisible()
  await expect(page.getByTestId('play-world')).toHaveAttribute('data-state', 'ready')
  const checkpoints = page.locator('.play-checkpoint-route').getByRole('button')
  const titles = ['Big data. Clear decisions.', 'Data at telecom scale.', 'Agents that connect.', 'Healthcare, connected.']
  await expect(checkpoints).toHaveCount(titles.length)
  for (const [index, title] of titles.entries()) {
    const checkpoint = checkpoints.nth(index)
    await expect(checkpoint).toBeVisible()
    await checkpoint.click()
    await expect(page.getByRole('dialog').getByRole('heading', { name: title, exact: true })).toBeVisible()
    await expect(page.getByRole('dialog').getByRole('heading', { name: 'The challenge', exact: true })).toBeVisible()
    await page.keyboard.press('Escape')
  }
})

test('a browser without canvas gets an explicit error and a usable portfolio', async ({ page }) => {
  await page.addInitScript(() => {
    Object.defineProperty(HTMLCanvasElement.prototype, 'getContext', { configurable: true, value: () => null })
  })
  await page.goto('/')
  const error = page.getByRole('alert')
  await expect(error).toContainText('Your browser couldn’t start the canvas.')
  await error.getByRole('link', { name: 'View portfolio', exact: true }).click()
  await expect(page.locator('#play-portfolio')).toBeVisible()
  await expect(page.locator('a[download]').first()).toHaveAttribute('href', '/resume/Roushan-Kumar-Resume.pdf')
})
