import { expect, test } from '@playwright/test'

test('Studio circle navigation, career details, and project stories are connected', async ({ page }) => {
  await page.goto('/studio/')
  await page.getByRole('link', { name: 'Explore résumé', exact: true }).click()
  await expect(page).toHaveURL(/#studio-resume$/)
  const career = page.locator('.studio-role').filter({ has: page.locator('.studio-role-title', { hasText: 'Senior Data Engineer' }) })
  await career.locator('summary').click()
  await expect(career).toHaveAttribute('open', '')
  await expect(career.locator('.studio-role-content')).toContainText('50%')
  await career.locator('summary').click()
  await expect(career).not.toHaveAttribute('open', '')
  await page.getByRole('link', { name: 'Explore projects', exact: true }).click()
  await expect(page).toHaveURL(/#studio-work$/)
  await page.getByRole('button', { name: 'Read case study: Healthcare, connected.', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await expect(dialog.getByRole('heading', { name: 'Healthcare, connected.', exact: true })).toBeVisible()
  await expect(dialog.getByText('An ongoing enterprise Data & AI initiative, led in the current role.', { exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(dialog).toHaveCount(0)
})

test('Studio exposes functional recruiter and contact dialogs', async ({ page }) => {
  await page.goto('/studio/')
  await page.getByRole('button', { name: 'Recruiter quick view', exact: true }).first().click()
  await expect(page.getByRole('dialog').getByRole('heading', { name: 'The 30-second introduction.', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Close dialog', exact: true }).click()
  await page.getByRole('button', { name: 'Start a conversation', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await expect(dialog.getByLabel('Your email')).toBeVisible()
  await expect(dialog.getByRole('link', { name: 'rkkr901@gmail.com', exact: true })).toHaveAttribute('href', 'mailto:rkkr901@gmail.com')
  await page.keyboard.press('Escape')
  await expect(dialog).toHaveCount(0)
})

test('Studio mobile menu supports Escape and section navigation', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'mobile', 'Mobile navigation only')
  await page.goto('/studio/')
  const open = page.getByRole('button', { name: 'Open navigation menu', exact: true })
  await open.click()
  await expect(page.getByRole('navigation', { name: 'Studio mobile navigation', exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(open).toBeFocused()
  await open.click()
  await page.getByRole('navigation', { name: 'Studio mobile navigation', exact: true }).getByRole('link', { name: 'Work' }).click()
  await expect(page).toHaveURL(/#studio-work$/)
  await expect(open).toHaveAttribute('aria-expanded', 'false')
})
